name: 'WordPress Plugin Check'
on: # rebuild any PRs and trunk branch changes
  pull_request:
  push:
    branches:
    - trunk

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build plugin
      run: |
        mv ${{ runner.temp }}/wordpress-indieauth/wordpress-indieauth ${{ runner.temp }}/wordpress-indieauth/indieauth
    - name: Run plugin check
      uses: wordpress/plugin-check-action@v1
      with:
        build-dir:  ${{ runner.temp }}/indieauth
        exclude-directories: |
          './bin'
          './.github'
          './node_modules'
          './vendor'
        exclude-checks: |
          'file_type'
